spring:
  application:
    name: library-test
  cloud:
    stream:
      schema:
        avro:
          dynamic-schema-generation-enabled: true
      bindings:
        output:
          destination: events
          content-type: application/*+avro
      kafka:
        binder:
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
                           